apiVersion: v1
kind: Pod
metadata:
  name: task-2
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: task-2
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
    - name: data
      mountPath: /data
    command:
    - "/bin/bash"
    - "-c"
    args:
    - "echo Pod started on $(date) >> /data/history && sleep 3600"


