apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-2
  name: task-2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: task-2
  type: LoadBalancer
