apiVersion: v1
kind: Pod
metadata:
  labels:
    run: task-3
  name: task-3
spec:
  containers:
  - image: nginx
    name: task-3
    ports:
    - containerPort: 80
      name: http
    livenessProbe:
      httpGet:
        port: 8080
