apiVersion: v1
kind: Pod
metadata:
  labels:
    run: task-2
  name: task-2
spec:
  containers:
  - image: marcmer/demo-app:v1
    name: demo-app
    ports:
    - containerPort: 8000
      name: http
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      name: http

