apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-1
  name: task-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-1
  template:
    metadata:
      labels:
        app: task-1
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-1
  name: task-1
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: task-1
  type: ClusterIP
