---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-1
  name: task-1
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: ?
  selector:
    app: ?
  type: ?