apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-1
  name: task-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: task-1
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 150m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-1
  name: task-1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: task-1
  type: ClusterIP