apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-svc
  name: example-svc
  namespace: default
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-svc
  type: ClusterIP
  #clusterIP: 10.111.167.140

