apiVersion: v1
kind: Pod
metadata:
  name: task-1
spec:
  restartPolicy: Never
  containers:
  - image: ubuntu
    name: ubuntu
    command:
    - "/bin/bash"
    - "-c"
    args:
    - "echo Hello participant"
