apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

configMapGenerator:
  - name: config
    files:
      - config.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: task-3
      spec:
        template:
          spec:
            volumes:
              - name: config
                configMap:
                  name: config
            containers:
              - name: task-3
                volumeMounts:
                  - name: config
                    mountPath: /etc/app/config/