apiVersion: v1
kind: Pod
metadata:
  name: task-2-1
  labels:
    run: task-2
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: run
            operator: In
            values:
            - task-2
        topologyKey: kubernetes.io/hostname
  containers:
  - name: task-2
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: task-2-2
  labels:
    run: task-2
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: run
            operator: In
            values:
            - task-2
        topologyKey: kubernetes.io/hostname
  containers:
  - name: task-2
    image: nginx
