apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: task-1
  labels:
    tier: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: webserver
  template:
    metadata:
      labels:
        tier: webserver
    spec:
      containers:
      - name: nginx
        image: nginx