apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-3
  name: task-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-3
  strategy: {}
  template:
    metadata:
      labels:
        app: task-3
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http

