apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: task-3-token
  annotations:
    kubernetes.io/service-account.name: task-3
---
apiVersion: v1
kind: Pod
metadata:
  name: task-3
spec:
  containers:
  - image: nginx
    name: task-3
  serviceAccountName: task-3
