apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-4
    version: "2"
  name: task-4-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-4
      version: "2"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: task-4
        version: "2"
    spec:
      containers:
      - image: marcmer/demo-app:v2
        name: demo-app
        ports:
        - containerPort: 8000
          name: http
