apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-4
  name: task-4
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: task-4
  type: LoadBalancer
