apiVersion: v1
kind: Pod
metadata:
  name: task-3-cm-env
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    env: 
    - name: MY_VAR
      valueFrom:
        configMapKeyRef:
          name: cm-task-3
          key: EXAMPLE_KEY
    command:
    - "/bin/bash"
    - "-c"
    args:
    - "while true; do echo The value of MY_VAR is $MY_VAR; sleep 1; done"

  
  