kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: custom-admin-scc
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny

