apiVersion: v1
kind: Pod
metadata:
  name: pod-with-node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: myorg.ch/disk
            operator: In
            values:
            - ssd          
  containers:
  - name: pod-with-node-affinity
    image: nginx

