apiVersion: v1
kind: Pod
metadata:
  name: load-generator-task-2
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while sleep 0.01; do wget -q -O- http://task-2; done
    image: busybox:1.28
    name: load-generator-task-2
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  